name: flutter_application_1
description: "Hizli Tasarim Modu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # âœ… TasarÄ±m ve ArayÃ¼z
  device_preview: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  wakelock_plus: ^1.1.0

  # âœ… Kamera ve KayÄ±t (AR ile uyumlu sÃ¼rÃ¼m)
  permission_handler: ^10.4.5
  camera: ^0.10.5+9
  shared_preferences: ^2.2.2

  # ðŸš€ AR ve Resim SeÃ§me
  ar_flutter_plugin: ^0.6.2
  image_picker: ^1.0.7
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/categories/
    - assets/templates/animals/
    - assets/templates/cars/
    - assets/templates/anime/
    - assets/templates/cartoon/
    - assets/templates/flowers/
    - assets/templates/human/
    - assets/templates/nature/
    - assets/tutorial/