name: iOS-Build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Flutter Kur
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Zorunlu Temizlik ve Bagimliliklar
        run: |
          flutter pub get
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod repo update
          pod install
          cd ..
        
      - name: iOS Build Al
        run: flutter build ios --release --no-codesign
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-dosyasi
          path: build/ios/iphoneos/Runner.app